### ISSUE TITLE
Integrating with  UICollectionViewDataSourcePrefetching

### ISSUE THREAD

**Issue by 8secz-johndpope** [sukov/CachingPlayerItem#2]
did you attempt to integrate with 
collectionview.isPrefetchingEnabled = true

```swift
extension VideoViewController: UICollectionViewDataSourcePrefetching {

    func collectionView(_ collectionView: UICollectionView, prefetchItemsAt indexPaths: [IndexPath]) {

        for indexPath in indexPaths {
            if let cell = feedCV.cellForItem(at: indexPath) as? VideoCollectionCell {
                cell.setUpPlayer()
            }
        }
    }

    func collectionView(_ collectionView: UICollectionView, cancelPrefetchingForItemsAt indexPaths: [IndexPath]) {
        // Cancel any requests for data for the specified index paths.
         // how can we target any rogue downloads if user jumps to another screen???
    }
}
```

**Comment by sukov** [comment]
Valid point! For now I would suggest to deinitialize the `CachingPlayerItem` in order to cancel the download request (not ideal, I know). Also please do feel free to contribute to this repo by opening a pull request with the updates that you need, otherwise you will have to wait for me to find the time to make this update.

**Comment by 8secz-johndpope** [comment]
@sukov  - fyi https://github.com/kean/Nuke/issues/448

**Comment by 8secz-johndpope** [comment]
fyi @bkg866

**Comment by sukov** [comment]
Feature added on the latest release, use version 1.1.1
