### ISSUE TITLE
this does not work with streaming urls youtube

### ISSUE THREAD

**Issue by 666bsw** [sukov/CachingPlayerItem#21]
this does not work with streaming urls youtube - the player does not start
with the playerItem = AVPlayerItem(url: url)  it works fine

**Comment by sukov** [comment]
Hello @666bsw. Since you did not provide any code, my educated guess is that you are trying to stream a youtube url directly, and not an actual url containing the .mp4 media. Or if you are trying to cache a live streaming media url, that is not supported as it is stated on the last line of the readme: 

“HTTP live streaming (HLS) M3U8 caching is not supported. You can only use init(nonCachingURL:) for playing M3U8.”
